### ISSUE TITLE
Fieldmap wrangler should provide more informative errors

### ISSUE THREAD

**Issue by effigies** [poldracklab/sdcflows#256]
See https://github.com/nipreps/fmriprep/issues/2679, https://github.com/nipreps/sdcflows/issues/227.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 324, in init_single_subject_wf
    fmap_estimators = find_estimators(
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/utils/wrangler.py", line 324, in find_estimators
    fm.FieldmapFile(fmap.path, metadata=fmap.get_metadata())
AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by mgxd** [comment]
we definitely should be checking for the existence of any `fmap` listed for correction

**Comment by effigies** [comment]
I think this is resolved by recent refactors. We no longer blindly generate `fmap` objects to a list.
