### ISSUE TITLE
Tracking LAS phasediff issue

### ISSUE THREAD

**Issue by effigies** [poldracklab/sdcflows#340]
### What happened?

From Neurostars user sabarnes I received a dataset with phasediff fieldmaps. This seemed potentially related to #325, but the BOLD/phasediff files have the same orientation/PE axis.

### What command did you use?

```shell
$ fmriprep-docker sourcedata/raw . participant --output-spaces T1w MNI152NLin2009cAsym \
    -w /data/scratch/fmriprep-sabarnes --debug fieldmaps -vv --config code/nipype.cfg \
    --notrack --patch smriprep=/home/chris/Projects/fmriprep-23_0/smriprep/smriprep \
    fmriprep=/home/chris/Projects/fmriprep-23_0/fmriprep/fmriprep \
    niworkflows=/home/chris/Projects/fmriprep-23_0/niworkflows/niworkflows \
    sdcflows=/home/chris/Projects/fmriprep-23_0/sdcflows/sdcflows --sloppy \
    --fs-no-reconall --participant-label 020 -t LexicalDecision

RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=23.0.1 -it \
    -v /home/chris/Projects/fmriprep-23_0/smriprep/smriprep:/opt/conda/lib/python3.9/site-packages/smriprep:ro \
    -v /home/chris/Projects/fmriprep-23_0/fmriprep/fmriprep:/opt/conda/lib/python3.9/s
ite-packages/fmriprep:ro \
    -v /home/chris/Projects/fmriprep-23_0/niworkflows/niworkflows:/opt/conda/lib/python3.9/site-packages/niworkflows:ro \
    -v /home/chris/Projects/fmriprep-23_0/sdcflows/sdcflows:/opt/conda/lib/python3.9/site-packages/sdcflows:ro \
    -v /home/chris/Documents/freesurfer_license.txt:/opt/freesurfer/license.txt:ro \
    -v /data/testing/fmriprep-neurostars-sabarnes/sourcedata/raw:/data:ro \
    -v /data/testing/fmriprep-neurostars-sabarnes:/out \
    -v /data/scratch/fmriprep-sabarnes:/scratch \
    -v /data/testing/fmriprep-neurostars-sabarnes/code/nipype.cfg:/home/fmriprep/.nipype/nipype.cfg:ro \
    nipreps/fmriprep:23.0.0rc0 /data /out participant --debug fieldmaps -vv --notrack \
    --sloppy --fs-no-reconall --participant-label 020 -t LexicalDecision -w /scratch \
    --output-spaces T1w MNI152NLin2009cAsym
```

### What version of fMRIPrep are you running?

23.0.0rc0 (patched)

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
230310-15:22:13,46 nipype.workflow INFO:                                                                                       
         [Node] Setting-up "fmriprep_23_0_wf.single_subject_020_wf.fmap_preproc_wf.wf_FM0.bs_filter" in "/scratch/fmriprep_23_0_wf/single_subject_020_wf/fmap_preproc_wf/wf_FM0/bs_filter".
230310-15:22:13,59 nipype.workflow INFO:
         [Node] Executing "bs_filter" <sdcflows.interfaces.bspline.BSplineApprox>
230310-15:22:13,201 nipype.interface INFO:
         Resampling image with resolution exceeding 'zooms_min' (2.5x2.5x2.5 → 4.0x4.0x4.0).
230310-15:22:13,312 nipype.workflow INFO:
         [Node] Finished "bs_filter", elapsed time 0.244008s.
230310-15:22:13,312 nipype.workflow WARNING:                                                                                   
         Storing result file without outputs
230310-15:22:13,313 nipype.workflow WARNING:
         [Node] Error on "fmriprep_23_0_wf.single_subject_020_wf.fmap_preproc_wf.wf_FM0.bs_filter" (/scratch/fmriprep_23_0_wf/single_subject_020_wf/fmap_preproc_wf/wf_FM0/bs_filter)
230310-15:22:14,676 nipype.workflow INFO:
         [Job 42] Completed (fmriprep_23_0_wf.single_subject_020_wf.anat_preproc_wf.anat_template_wf.anat_conform).
230310-15:22:14,676 nipype.workflow INFO:
         [Job 93] Completed (fmriprep_23_0_wf.single_subject_020_wf.fmap_preproc_wf.wf_FM2.phdiff_wf.compfmap).
230310-15:22:14,678 nipype.workflow ERROR:
         Node bs_filter failed to run on host ac5e290ca5c4.                                                                    
230310-15:22:14,678 nipype.workflow ERROR:   
         Saving crash info to /out/sub-020/log/20230310-152125_e9f102d3-4210-4f29-92a9-288ff8476345/crash-20230310-152214-root-bs_filter-9ed1d984-b646-4a9e-80c8-b947263a88a6.txt
Traceback (most recent call last):        
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)  
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node bs_filter.
                                                               
Traceback:                                                   
        Traceback (most recent call last):  
          File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
            runtime = self._run_interface(runtime)
          File "/opt/conda/lib/python3.9/site-packages/sdcflows/interfaces/bspline.py", line 187, in _run_interface                                                                                                                                                       data -= np.squeeze(mode(data[mask]).mode)                                                                          
        ValueError: operands could not be broadcast together with shapes (52,52,32) (0,) (52,52,32)
```

**Comment by effigies** [comment]
The issue seems to be with extremely poor masking of the magnitude images, driven by a very low-SNR `magnitude2` image. Deleting it passes this step. We'll see if the final result is sensible.

**Comment by oesteban** [comment]
I have been very strongly considering synthstrip ... :sweat:

**Comment by effigies** [comment]
IMO we just don't need to merge magnitude images. Magnitude1, which is required for phase1/2 and phasediff, seems like it should be enough.
