### ISSUE TITLE
Slightly rotated phase1/phase2 images should not fail to be aligned

### ISSUE THREAD

**Issue by katseitz** [poldracklab/sdcflows#347]
### What happened?

When running fmriprep with fieldmaps for distortion correction, no functional reports were outputted due to "Affine for image 1 foes not match affine for first image" error. T1W output looks great. 

### What command did you use?

```shell
sbatch 23_fmriprep.sh:
singularity run --cleanenv -B /MY_PATH \
/MY_PATH/singularity_images/fmriprep-23.0.1.simg \
/MY_PATH/data/raw/neuroimaging/bids \
/MY_PATH/data/processed/neuroimaging/23_fmriprep participant \
--participant-label ${1} --fs-license-file /MY_PATH/software/freesurfer_license/license.txt \
-w /MY_PATH/data/processed/neuroimaging/work


Called using sbatch 23_fmriprep.sh sub-9999
```

### What version of fMRIPrep are you running?

23.0.1, but we have recreated this error in 21 and 22 as well.

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: fmriprep_23_0_wf.single_subject_9999_wf.fmap_preproc_wf.wf_auto_00000.magnitude_wf.magmrg
Working directory: /MY_PATH/data/processed/neuroimaging/work/fmriprep_23_0_wf/single_subject_9999_wf/fmap_preproc_wf/wf_auto_00000/magnitude_wf/magmrg

Node inputs:

grand_mean_scaling = False
hmc = False
in_files = ['/MY_PATH/data/raw/neuroimaging/bids/sub-t1143/ses-1/fmap/sub-9999_ses-1_magnitude1.nii.gz', '/MY_PATH/data/raw/neuroimaging/bids/sub-t1143/ses-1/fmap/sub-9999_ses-1_magnitude2.nii.gz']
in_mask = <undefined>
to_ras = False
zero_based_avg = True

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node magmrg.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/images.py", line 149, in _run_interface
	    filenii = nb.concat_images(nii_list)
	  File "/opt/conda/lib/python3.9/site-packages/nibabel/funcs.py", line 138, in concat_images
	    raise ValueError(f'Affine for image {i} does not match affine for first image')
	ValueError: Affine for image 1 does not match affine for first image
```

### Additional information / screenshots

Data quality for this study is tricky -- participants are children and move a lot and there are distortions in the magnetic field that are causing warping. Are our participants just moving too much to be able to apply to fmaps? I should add, this is all from a GE scanner and it has been more complicated than normal getting this data into bids format.

**Comment by effigies** [comment]
What is your fieldmap? phase1+phase2 or phasediff? I'm a bit surprised to see differences in affine for magnitude1 and magnitude2. Would you mind sharing the `fslhd` output for all of your fieldmap images?

**Comment by katseitz** [comment]
Phase1, phase2, mag1, mag2. Thanks for your quick response!

<details><summary>Phase1:</summary>

```
sizeof_hdr     348
data_type      INT16
dim0           3
dim1           88
dim2           88
dim3           51
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        2.500000
pixdim2        2.500000
pixdim3        2.500000
pixdim4        0.731000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      2
freq_dim       1
slice_dim      3
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      -2.499968  -0.000000  0.012729  108.680000
qto_xyz:2      -0.001346  2.485991  -0.264286  -74.115219
qto_xyz:3      0.012657  0.264289  2.485959  -96.458961
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Right-to-Left
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      -2.499968  0.000000  0.012735  108.680000
sto_xyz:2      -0.001346  2.485991  -0.264287  -74.115219
sto_xyz:3      0.012664  0.264289  2.485972  -96.458961
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip        TE=4.9;Time=171221.000
aux_file 
```

</details>
<details><summary>Phase2:</summary>

```
sizeof_hdr     348
data_type      INT16
dim0           3
dim1           88
dim2           88
dim3           51
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        2.500000
pixdim2        2.500000
pixdim3        2.500000
pixdim4        0.731000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      2
freq_dim       1
slice_dim      3
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      -2.499968  -0.000001  0.012711  108.680000
qto_xyz:2      -0.001345  2.485991  -0.264287  -74.115189
qto_xyz:3      0.012640  0.264290  2.485959  -96.459038
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Right-to-Left
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      -2.499968  0.000000  0.012735  108.680000
sto_xyz:2      -0.001346  2.485991  -0.264288  -74.115189
sto_xyz:3      0.012664  0.264290  2.485971  -96.459038
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip        TE=7.1;Time=171407.000
aux_file 
```

</details>
<details><summary>Mag1:</summary>

```
sizeof_hdr     348
data_type      INT16
dim0           3
dim1           88
dim2           88
dim3           51
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        2.500000
pixdim2        2.500000
pixdim3        2.500000
pixdim4        0.731000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      2
freq_dim       1
slice_dim      3
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      -2.499968  -0.000000  0.012729  108.680000
qto_xyz:2      -0.001346  2.485991  -0.264286  -74.115219
qto_xyz:3      0.012657  0.264289  2.485959  -96.458961
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Right-to-Left
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      -2.499968  0.000000  0.012735  108.680000
sto_xyz:2      -0.001346  2.485991  -0.264287  -74.115219
sto_xyz:3      0.012664  0.264289  2.485972  -96.458961
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip        TE=4.9;Time=171221.000
aux_file 
```

</details>
<details><summary>Mag2:</summary>

```
sizeof_hdr     348
data_type      INT16
dim0           3
dim1           88
dim2           88
dim3           51
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        2.500000
pixdim2        2.500000
pixdim3        2.500000
pixdim4        0.731000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      2
freq_dim       1
slice_dim      3
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      -2.499968  -0.000001  0.012711  108.680000
qto_xyz:2      -0.001345  2.485991  -0.264287  -74.115189
qto_xyz:3      0.012640  0.264290  2.485959  -96.459038
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Right-to-Left
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      -2.499968  0.000000  0.012735  108.680000
sto_xyz:2      -0.001346  2.485991  -0.264288  -74.115189
sto_xyz:3      0.012664  0.264290  2.485971  -96.459038
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip        TE=7.1;Time=171407.000
aux_file  

```

</details>

**Comment by effigies** [comment]
Thanks for this. I think we probably over-zealously combined the phasediff+magnitude1/2 and phase1/2+magnitude1/2 workflows. This should be fixable, and if you are able to share data, I can verify it. I think you could probably also fall back to fMRIPrep 20.2.7 (the long-term support release series).

**Comment by katseitz** [comment]
Just sent you an email.

**Comment by effigies** [comment]
@katseitz I looked at your files and they are aligned, so the issue is just that their affines for some reason are not quite lined up. I had imagined that we would want to register the two images together, but that would introduce unnecessary resampling.

I think the thing to do will be for us to verify that the images are in register and then ignore the affine information when concatenating.

In the short term, you could use fslcpgeom to copy the header from phase1/magnitude1 to phase2/magnitude2:

```
$ fslcpgeom sub-t1143/ses-1/fmap/sub-t1143_ses-1_magnitude{1,2}.nii.gz
$ fslcpgeom sub-t1143/ses-1/fmap/sub-t1143_ses-1_phase{1,2}.nii.gz
```

**Comment by katseitz** [comment]
Thanks, @effigies! Hmm... is this an oddity from the scanner? I am hoping it's not from my data management and preprocessing... 

And just to make sure I'm understanding correctly -- in a future release, you all plan to verify that the images are in register and then ignore the affine information. In the mean time, we can run fmriprep after copying headers from phase1/magnitude1 to phase2/magnitude2? We can absolutely do this. I'm assuming once we do this, we can run the most recent version? Again, thank you so much for your help.

**Comment by effigies** [comment]
I imagine it's from the scanner, but it's rarely a bad idea to review your conversion scripts and possibly rerun to make sure you get the same results.

> And just to make sure I'm understanding correctly -- in a future release, you all plan to verify that the images are in register and then ignore the affine information. In the mean time, we can run fmriprep after copying headers from phase1/magnitude1 to phase2/magnitude2? 

Correct.

> I'm assuming once we do this, we can run the most recent version?

Yes.

**Comment by katseitz** [comment]
Amazing! Glad we have a path forward. Would it be possible to update this ticket when the version with the fix is released or should I just monitor for the next version?

**Comment by effigies** [comment]
Yes, we'll keep this open until it's fixed.
