### ISSUE TITLE
CLI run requires mriqc to be installed

### ISSUE THREAD

**Issue by miltoncamacho** [poldracklab/sdcflows#468]
### What happened?

When running sdcflows CLI command, I get an error `No module named 'mriqc'`. 

If I run the container interactively and install the mriqc using `pip install mriqc` the issue is resolved. I am sure there is an excellent reason why mriqc is necessary, so perhaps this needs to be added to the requirements.txt

### What command did you use?

```shell
sdcflows /bids-input /bids-output participant --debug
```

### What version of the software are you running?

2.10.0

### How are you running this software?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
(sdcflows) root@91f133b4405b:/tmp# sdcflows /bids-input /bids-output participant --debug
241030-17:10:41,542 cli IMPORTANT:
	 Running SDCFlows 2.10.0:
             * BIDS dataset path: /bids-input.
             * Output folder: /bids-output.
             * Analysis levels: ['participant'].

Traceback (most recent call last):
  File "/opt/conda/envs/sdcflows/bin/sdcflows", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/sdcflows/lib/python3.10/site-packages/sdcflows/cli/main.py", line 178, in main
    "plugin": MultiProcPlugin(
  File "/opt/conda/envs/sdcflows/lib/python3.10/site-packages/niworkflows/engine/plugin.py", line 416, in __init__
    from mriqc import config
ModuleNotFoundError: No module named 'mriqc'
```

**Comment by effigies** [comment]
Can you upgrade `niworkflows`?

**Comment by effigies** [comment]
Sorry, just to be more explicit, this bug was fixed in https://github.com/nipreps/niworkflows/pull/876 and released in niworkflows 1.11.0.

**Comment by miltoncamacho** [comment]
Thanks

see #469
